### ISSUE TITLE
Loading spinner for app loading

### ISSUE THREAD

**Issue by ChristianWeyer** [thinktecture/windows-developer-cross-platform-article-series#4]
Instead of 'Loading...' - maybe this:
https://projects.lukehaas.me/css-loaders/

The one in the lower right corner.

Centered vertically and horizontally in the middle of the screen With the TT color :-)

**Comment by ChristianWeyer** [comment]
@ManuelRauber Maybe something like this?
https://github.com/thinktecture/windows-developer-cross-platform-article-series/tree/loader

**Comment by ManuelRauber** [comment]
Done with sexyness
